### ISSUE TITLE
Cannot run demo

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-swift-sample#1]
I have this setup: macOS Catalina 10.15.2, Xcode 11.3 and iPhone 8. 

I have followed steps how to run this demo project, but I get some errors. I do not have experience with iOS development so I am new to this and I am not sure what could be wrong. I have `run pod try Tangram-es` and got an error: `NoMethodError - undefined method `root' for false:FalseClass`. 

Also I tried to run this demo project on iPhone 8 (not simulator) and I got error: `Failure Reason: The application bundle does not contain a valid identifier.` despite I set bundle ID as is written in step 2. I have also done all what is described in instructions, but I got this error. I am not sure what could be wrong.

**Comment by matteblair** [comment]
I realized that the `Podfile` wasn't using the latest version of Tangram ES, it used a version that was missing a framework bundle identifier. 

I just updated the version in the `Podfile` so this should be resolved now if you pull `master` and re-run `pod install`.

**Comment by rwrx** [comment]
Thank you a lot. Now it is working properly.
