### ISSUE TITLE
Bitcode error while creating an archive

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-swift-sample#3]
I have tried to create archive from this Tangram demo app in Xcode and I got this error: 

`ld: bitcode bundle could not be generated because '/Users/tom/Tomas/Programovanie/Git/tangram-swift-sample/Pods/Tangram-es/TangramMap.framework/TangramMap' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/tom/Tomas/Programovanie/Git/tangram-swift-sample/Pods/Tangram-es/TangramMap.framework/TangramMap' for architecture arm64`

I am using this project without any modification, so the `TangramMap` framework is added as a Pod module. What could be wrong? Thank you.

**Comment by matteblair** [comment]
I'll try to reproduce this on my end. We should probably have an automated check for bitcode in our CI scripts so that this doesn't break in the future :\

**Comment by matteblair** [comment]
Ok! I was able to reproduce the issue immediately. This is a problem with the Tangram ES build process and I'll discuss more in a related issue there: https://github.com/tangrams/tangram-es/issues/2056

**Comment by rwrx** [comment]
@matteblair yes, that's great, that you have fixed it. I have tried this fix also and I was able to create archive in Xcode. Thank you a lot. So I will close this issue as it is also tracked in Tangram-ES repo.
